FROM node:16-alpine

RUN mkdir -p /var/www/gateway
WORKDIR /var/www/gateway
ADD . /var/www/gateway
RUN yarn config set network-timeout 600000 -g
EXPOSE 8000
RUN yarn install
RUN yarn build
CMD [ "yarn", "start:prod" ]
    